version: "3.8"

services:
  dept-faiss-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: dept-faiss-backend
    container_name: dept-faiss-backend
    env_file:
      - /home/shduser/Docker_static/dept-faiss-backend/.env
    networks:
      web:
        aliases:
          - dept-faiss-backend
    expose: ["80"]
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 512M


networks:
  web:
    external: true
    name: shdnetwork
